/*
 * Program: fileManip.c
 * Name: Mark Erle
 * UID: merle
 *
 * DO NOT EDIT THIS FILE
 */

#include <stdio.h>          /* for FILE type */
#include "globalDefs.h"     /* for qbu_t type and MSG_LENGTH */
#include "syscalls.h"       /* for wrapped system calls */
#include "fileManipFuncs.h" /* for support functions */
#include "printMsgs.h"      /* for printMsgs function */

int main(int argc, char *argv[], char *envp[]) {
  FILE *rFile;              /* remote file */
  FILE *cFile;              /* commands file */
  FILE *lFile;              /* local file */
  long totalBytes;          /* bytes copied */
  qbu_t msg[MSG_LENGTH];    /* secret messages */
  
  parseArgsAndOpenFiles(argc, argv, &rFile, &cFile);    /* read command-line arguments and open files */
  totalBytes = copyFile(argv[1], rFile, envp, &lFile);  /* copy remote file to local file, close remote file, rewind local file */
  runCmds(lFile, cFile, totalBytes, msg);               /* run commands in commands file on local file, close local and commands file */
  printMsg(argv[1], envp, msg);                         /* print secret message */

  return 0;
}
