/*
 * Program: fileManipFuncs.h
 * Name: Mark Erle
 * UID: merle
 *
 * DO NOT EDIT THIS FILE
 */

#ifndef FILEMANIPFUNCS_H
#define FILEMANIPFUNCS_H

#include <stdio.h>       /* for FILE type */
#include "globalDefs.h"  /* for qbut_t type */

void   parseArgsAndOpenFiles(int argc, char *argv[], FILE **lFile, FILE **cFile); 
long   copyFile(char *rFileName, FILE *rFile, char *envp[], FILE **lFile);
void   runCmds(FILE *lFile, FILE *cFile, long totalCount, qbu_t msg[]);

#endif
