/* 
 * Program: printMsgs.h
 * Name: Mark Erle
 * UID: merle
 *
 * DO NOT EDIT THIS FILE
 */

#ifndef PRINTMSGS_H
#define PRINTMSGS_H

#include "globalDefs.h" /* for qbu_t type */

void   printMsg(char *rFile, char *env[], qbu_t msg[]);

#endif
