/* 
 * Program: syscalls.h
 * Name: Mark Erle
 * UID: merle
 *
 * DO NOT EDIT THIS FILE
 */

#ifndef SYSCALLS_H
#define SYSCALLS_H

#include <stdio.h>           /* for FILE type */
#include <dirent.h>          /* for struct dirent type and DIR type */

FILE  *Fopen(const char *path, const char *mode);
void Fclose(FILE *fp);
int Fseek(FILE *fp, long offset, int whence);
long Ftell(FILE *fp);
size_t Fread(void *ptr, size_t itemSize, size_t numItems, FILE *fp);
size_t Fwrite(const void *ptr, size_t itemSize, size_t numItems, FILE *fp);
void *Malloc(size_t bytes);
int Chdir(const char *path);
DIR *Opendir(const char *name);
struct dirent *Readdir(DIR *dirp);
int Closedir(DIR *dirp);

#endif
